"""Constantes de negocio del sistema."""

ESTADO_RECIBIDO = "RECIBIDO"
ESTADO_PREASIGNADO = "PREASIGNADO"
ESTADO_ASIGNADO_FINAL = "ASIGNADO_FINAL"
ESTADO_RECHAZADO_RVE = "RECHAZADO_RVE"
ESTADO_CANCELADO = "CANCELADO"
ESTADO_COMPLETADO = "COMPLETADO"
ESTADO_ACEPTADO_RVE = "ACEPTADO_RVE"
ESTADO_MANUAL = "MANUAL"
ESTADO_URGENTE_GESTIONAR_MANUAL = "URGENTE_GESTIONAR_MANUAL"

ESTADOS_ACEPTADOS = {ESTADO_PREASIGNADO, ESTADO_ASIGNADO_FINAL, ESTADO_ACEPTADO_RVE}
ESTADOS_TERMINALES = {ESTADO_RECHAZADO_RVE, ESTADO_CANCELADO, ESTADO_COMPLETADO}
ESTADOS_MANUALES = {ESTADO_MANUAL, ESTADO_URGENTE_GESTIONAR_MANUAL}

TIPO_ENRUTAMIENTO_AUTOMATICO = "AUTOMATICO"
TIPO_ENRUTAMIENTO_MANUAL = "MANUAL"
TIPOS_ENRUTAMIENTO = {TIPO_ENRUTAMIENTO_AUTOMATICO, TIPO_ENRUTAMIENTO_MANUAL}

ANALISIS_DATOS_ERRONEOS = "DATOS ERRONEOS"
ANALISIS_SERVICIO_EMERGENCIA = "SERVICIO EMERGENCIA"
ANALISIS_SIN_DISPONIBILIDAD_TURNOS = "SIN DISPONIBILIDAD TURNOS"
ANALISIS_SERVICIO_FUERA_LIMITES_TURNO = "SERVICIO FUERA DE LIMITES DEL TURNO"
ANALISIS_FUERA_RADIO_MAXIMO = "FUERA DE RADIO MAXIMO"
ANALISIS_SATURACION_TURNO = "SATURACION_TURNO"
ANALISIS_NO_LLEGA_TIEMPO = "NO LLEGA A TIEMPO"
ANALISIS_INSERCION_NO_FACTIBLE = "INSERCION NO FACTIBLE"
ANALISIS_OTRO_RECHAZO = "OTRO RECHAZO"
SERVICIOS_ANALISIS_COLUMN = "AH"
SERVICIOS_ANALISIS_INDEX = 33

PREASIGNACION_ACTIVA = "ACTIVA"
PREASIGNACION_CONGELADA = "CONGELADA"
PREASIGNACION_CANCELADA = "CANCELADA"

NOMBRE_CONDUCTOR_PENDIENTE = "A ESPERA DE ASIGNACION TECNICO"
